-- AlterTable
ALTER TABLE "Payroll" ADD COLUMN     "attendanceDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "daysInMonth" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "earnedGross" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "grossSalary" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "leaveDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "otherDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "payableDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pfDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "profTaxDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "weekendDays" INTEGER NOT NULL DEFAULT 0;
